version: '3.9'

services:
  DB-02:
    image: postgres
    container_name: DB-02
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'DB-02:/var/lib/postgresql/data'

volumes:
  DB-02: