version: '3.9'

services:
  DB-01:
    image: postgres
    container_name: DB-01
    ports:
      - '5432:5432'
    env_file:
      - .env
    volumes:
      - 'DB-01:/var/lib/postgresql/data'

volumes:
  DB-01: